//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenhouse_products
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class greenhouse_productEntities : DbContext
    {
        public greenhouse_productEntities()
            : base("name=greenhouse_productEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Виды_продукции> Виды_продукции { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Пользователь_заказ> Пользователь_заказ { get; set; }
        public virtual DbSet<Продукция> Продукция { get; set; }
        public virtual DbSet<Роль> Роль { get; set; }
        public virtual DbSet<Статус> Статус { get; set; }
    }
}
