//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenhouse_products
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Продуция_заказ = new HashSet<Продуция_заказ>();
        }
    
        public int Номер { get; set; }
        public string Адрес { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public Nullable<System.DateTime> Дата_оформления { get; set; }
        public Nullable<int> Статус { get; set; }
        public Nullable<int> Пользователь { get; set; }
    
        public virtual Пользователь Пользователь1 { get; set; }
        public virtual Статус Статус1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продуция_заказ> Продуция_заказ { get; set; }
    }
}
