//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenhouse_products
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь_заказ
    {
        public int Номер { get; set; }
        public Nullable<int> Пользователь { get; set; }
        public Nullable<int> Заказ { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Заказ Заказ1 { get; set; }
        public virtual Пользователь Пользователь1 { get; set; }
    }
}
