//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenhouse_products
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public int Номер { get; set; }
        public string Почта { get; set; }
        public string Пароль { get; set; }
        public string Адрес { get; set; }
        public Nullable<int> Роль { get; set; }
        public Nullable<int> Заказ { get; set; }
    
        public virtual Заказ Заказ1 { get; set; }
        public virtual Роль Роль1 { get; set; }
    }
}
