//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greenhouse_products
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        public int Номер { get; set; }
        public byte[] Изображение { get; set; }
        public string Наименование { get; set; }
        public int Вес { get; set; }
        public decimal Цена { get; set; }
        public Nullable<int> Вид_продукции { get; set; }
    
        public virtual Виды_продукции Виды_продукции { get; set; }
    }
}
